export const SCART_ADD_ITEM = 'SCART_ADD_ITEM';
export const SCART_REMOVE_ITEM = 'SCART_REMOVE_ITEM';
export const SCART_SAVE_SHIPPING = 'SCART_SAVE_SHIPPING';
export const SCART_SAVE_PAYMENT = 'SCART_SAVE_PAYMENT';