export const SCATEGORY_LIST_REQUEST = "SCATEGORY_LIST_REQUEST"
export const SCATEGORY_LIST_SUCCESS = "SCATEGORY_LIST_SUCCESS"
export const SCATEGORY_LIST_FAIL = "SCATEGORY_LIST_FAIL"

export const SCATEGORY_DETAILS_REQUEST = "SCATEGORY_DETAILS_REQUEST"
export const SCATEGORY_DETAILS_SUCCESS = "SCATEGORY_DETAILS_SUCCESS"
export const SCATEGORY_DETAILS_FAIL = "SCATEGORY_DETAILS_FAIL"

export const SCATEGORY_SAVE_REQUEST = "SCATEGORY_SAVE_REQUEST";
export const SCATEGORY_SAVE_SUCCESS = "SCATEGORY_SAVE_SUCCESS";
export const SCATEGORY_SAVE_FAIL = "SCATEGORY_SAVE_FAIL";

export const SCATEGORY_UPDATE_REQUEST = "SCATEGORY_UPDATE_REQUEST";
export const SCATEGORY_UPDATE_SUCCESS = "SCATEGORY_UPDATE_SUCCESS";
export const SCATEGORY_UPDATE_FAIL = "SCATEGORY_UPDATE_FAIL";

export const SCATEGORY_DELETE_REQUEST = "SCATEGORY_DELETE_REQUEST";
export const SCATEGORY_DELETE_SUCCESS = "SCATEGORY_DELETE_SUCCESS";
export const SCATEGORY_DELETE_FAIL = "SCATEGORY_DELETE_FAIL";

