export const SINSTRUMENT_LIST_REQUEST = "SINSTRUMENT_LIST_REQUEST";
export const SINSTRUMENT_LIST_SUCCESS = "SINSTRUMENT_LIST_SUCCESS";
export const SINSTRUMENT_LIST_FAIL = "SINSTRUMENT_LIST_FAIL";

export const SINSTRUMENT_LIST_CATEGORY_REQUEST = "SINSTRUMENT_LIST_CATEGORY_REQUEST";
export const SINSTRUMENT_LIST_CATEGORY_SUCCESS = "SINSTRUMENT_LIST_CATEGORY_SUCCESS";
export const SINSTRUMENT_LIST_CATEGORY_FAIL = "SINSTRUMENT_LIST_CATEGORY_FAIL";

export const SINSTRUMENT_DETAILS_REQUEST = "SINSTRUMENT_DETAILS_REQUEST";
export const SINSTRUMENT_DETAILS_SUCCESS = "SINSTRUMENT_DETAILS_SUCCESS";
export const SINSTRUMENT_DETAILS_FAIL = "SINSTRUMENT_DETAILS_FAIL";

export const SINSTRUMENT_SAVE_REQUEST = "SINSTRUMENT_SAVE_REQUEST";
export const SINSTRUMENT_SAVE_SUCCESS = "SINSTRUMENT_SAVE_SUCCESS";
export const SINSTRUMENT_SAVE_FAIL = "SINSTRUMENT_SAVE_FAIL";

export const SINSTRUMENT_UPDATE_REQUEST = "SINSTRUMENT_UPDATE_REQUEST";
export const SINSTRUMENT_UPDATE_SUCCESS = "SINSTRUMENT_UPDATE_SUCCESS";
export const SINSTRUMENT_UPDATE_FAIL = "SINSTRUMENT_UPDATE_FAIL";

export const SINSTRUMENT_DELETE_REQUEST = "SINSTRUMENT_DELETE_REQUEST";
export const SINSTRUMENT_DELETE_SUCCESS = "SINSTRUMENT_DELETE_SUCCESS";
export const SINSTRUMENT_DELETE_FAIL = "SINSTRUMENT_DELETE_FAIL";



