export const SORDER_CREATE_REQUEST = "SORDER_CREATE_REQUEST";
export const SORDER_CREATE_SUCCESS = "SORDER_CREATE_SUCCESS";
export const SORDER_CREATE_FAIL = "SORDER_CREATE_FAIL";

export const SORDER_DETAILS_REQUEST = "SORDER_DETAILS_REQUEST";
export const SORDER_DETAILS_SUCCESS = "SORDER_DETAILS_SUCCESS";
export const SORDER_DETAILS_FAIL = "SORDER_DETAILS_FAIL";

export const MY_SORDER_LIST_REQUEST = "MY_SORDER_LIST_REQUEST";
export const MY_SORDER_LIST_SUCCESS = "MY_SORDER_LIST_SUCCESS";
export const MY_SORDER_LIST_FAIL = "MY_SORDER_LIST_FAIL";

export const SORDER_LIST_REQUEST = "SORDER_LIST_REQUEST";
export const SORDER_LIST_SUCCESS = "SORDER_LIST_SUCCESS";
export const SORDER_LIST_FAIL = "SORDER_LIST_FAIL";

export const SORDER_PAY_REQUEST = "SORDER_PAY_REQUEST";
export const SORDER_PAY_SUCCESS = "SORDER_PAY_SUCCESS";
export const SORDER_PAY_FAIL = "SORDER_PAY_FAIL";

export const SORDER_DELETE_REQUEST = "SORDER_DELETE_REQUEST";
export const SORDER_DELETE_SUCCESS = "SORDER_DELETE_SUCCESS";
export const SORDER_DELETE_FAIL = "SORDER_DELETE_FAIL";