
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const FARMER_REGISTER_REQUEST = "FARMER_REGISTER_REQUEST";
export const FARMER_REGISTER_SUCCESS = "FARMER_REGISTER_SUCCESS";
export const FARMER_REGISTER_FAIL = "FARMER_REGISTER_FAIL";

export const HOLESELLER_REGISTER_REQUEST = "HOLESELLER_REGISTER_REQUEST";
export const HOLESELLER_REGISTER_SUCCESS = "HOLESELLER_REGISTER_SUCCESS";
export const HOLESELLER_REGISTER_FAIL = "HOLESELLER_REGISTER_FAIL";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAIL = "ADMIN_REGISTER_FAIL";

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const FARMER_LIST_REQUEST = "FARMER_LIST_REQUEST"
export const FARMER_LIST_SUCCESS = "FARMER_LIST_SUCCESS"
export const FARMER_LIST_FAIL = "FARMER_LIST_FAIL"

export const HOLESELLER_LIST_REQUEST = "HOLESELLER_LIST_REQUEST"
export const HOLESELLER_LIST_SUCCESS = "HOLESELLER_LIST_SUCCESS"
export const HOLESELLER_LIST_FAIL = "HOLESELLER_LIST_FAIL"

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

export const FIND_USER_REQUEST = "FIND_USER_REQUEST";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAIL = "FIND_USER_FAIL";

export const USER_PROFILE_DETAILS_REQUEST = 'USER_PROFILE_DETAILS_REQUEST';
export const USER_PROFILE_DETAILS_SUCCESS = 'USER_PROFILE_DETAILS_SUCCESS';
export const USER_PROFILE_DETAILS_FAIL = 'USER_PROFILE_DETAILS_FAIL';

export const USER_PASSWORD_UPDATE_REQUEST = 'USER_PASSWORD_UPDATE_REQUEST';
export const USER_PASSWORD_UPDATE_SUCCESS = 'USER_PASSWORD_UPDATE_SUCCESS';
export const USER_PASSWORD_UPDATE_FAIL = 'USER_PASSWORD_UPDATE_FAIL';

export const LOGOUT = 'LOGOUT';