export const BCART_ADD_ITEM = 'BCART_ADD_ITEM';
export const BCART_REMOVE_ITEM = 'BCART_REMOVE_ITEM';
export const BCART_SAVE_SHIPPING = 'BCART_SAVE_SHIPPING';
export const BCART_SAVE_PAYMENT = 'BCART_SAVE_PAYMENT';