export const BCATEGORY_LIST_REQUEST = "BCATEGORY_LIST_REQUEST"
export const BCATEGORY_LIST_SUCCESS = "BCATEGORY_LIST_SUCCESS"
export const BCATEGORY_LIST_FAIL = "BCATEGORY_LIST_FAIL"

export const BCATEGORY_DETAILS_REQUEST = "BCATEGORY_DETAILS_REQUEST"
export const BCATEGORY_DETAILS_SUCCESS = "BCATEGORY_DETAILS_SUCCESS"
export const BCATEGORY_DETAILS_FAIL = "BCATEGORY_DETAILS_FAIL"

export const BCATEGORY_SAVE_REQUEST = "BCATEGORY_SAVE_REQUEST";
export const BCATEGORY_SAVE_SUCCESS = "BCATEGORY_SAVE_SUCCESS";
export const BCATEGORY_SAVE_FAIL = "BCATEGORY_SAVE_FAIL";

export const BCATEGORY_UPDATE_REQUEST = "BCATEGORY_UPDATE_REQUEST";
export const BCATEGORY_UPDATE_SUCCESS = "BCATEGORY_UPDATE_SUCCESS";
export const BCATEGORY_UPDATE_FAIL = "BCATEGORY_UPDATE_FAIL";

export const BCATEGORY_DELETE_REQUEST = "BCATEGORY_DELETE_REQUEST";
export const BCATEGORY_DELETE_SUCCESS = "BCATEGORY_DELETE_SUCCESS";
export const BCATEGORY_DELETE_FAIL = "BCATEGORY_DELETE_FAIL";

