export const BORDER_CREATE_REQUEST = "BORDER_CREATE_REQUEST";
export const BORDER_CREATE_SUCCESS = "BORDER_CREATE_SUCCESS";
export const BORDER_CREATE_FAIL = "BORDER_CREATE_FAIL";

export const BORDER_DETAILS_REQUEST = "BORDER_DETAILS_REQUEST";
export const BORDER_DETAILS_SUCCESS = "BORDER_DETAILS_SUCCESS";
export const BORDER_DETAILS_FAIL = "BORDER_DETAILS_FAIL";

export const MY_BORDER_LIST_REQUEST = "MY_BORDER_LIST_REQUEST";
export const MY_BORDER_LIST_SUCCESS = "MY_BORDER_LIST_SUCCESS";
export const MY_BORDER_LIST_FAIL = "MY_BORDER_LIST_FAIL";

export const FARMER_GET_BORDER_LIST_REQUEST = "FARMER_GET_BORDER_LIST_REQUEST";
export const FARMER_GET_BORDER_LIST_SUCCESS = "FARMER_GET_BORDER_LIST_SUCCESS";
export const FARMER_GET_BORDER_LIST_FAIL = "FARMER_GET_BORDER_LIST_FAIL";

export const BORDER_LIST_REQUEST = "BORDER_LIST_REQUEST";
export const BORDER_LIST_SUCCESS = "BORDER_LIST_SUCCESS";
export const BORDER_LIST_FAIL = "BORDER_LIST_FAIL";

export const BORDER_PAY_REQUEST = "BORDER_PAY_REQUEST";
export const BORDER_PAY_SUCCESS = "BORDER_PAY_SUCCESS";
export const BORDER_PAY_FAIL = "BORDER_PAY_FAIL";

export const BORDER_DELETE_REQUEST = "BORDER_DELETE_REQUEST";
export const BORDER_DELETE_SUCCESS = "BORDER_DELETE_SUCCESS";
export const BORDER_DELETE_FAIL = "BORDER_DELETE_FAIL";