export const BPRODUCT_LIST_REQUEST = "BPRODUCT_LIST_REQUEST";
export const BPRODUCT_LIST_SUCCESS = "BPRODUCT_LIST_SUCCESS";
export const BPRODUCT_LIST_FAIL = "BPRODUCT_LIST_FAIL";

export const BPRODUCT_LIST_CATEGORY_REQUEST = "BPRODUCT_LIST_CATEGORY_REQUEST";
export const BPRODUCT_LIST_CATEGORY_SUCCESS = "BPRODUCT_LIST_CATEGORY_SUCCESS";
export const BPRODUCT_LIST_CATEGORY_FAIL = "BPRODUCT_LIST_CATEGORY_FAIL";

export const BPRODUCT_DETAILS_REQUEST = "BPRODUCT_DETAILS_REQUEST";
export const BPRODUCT_DETAILS_SUCCESS = "BPRODUCT_DETAILS_SUCCESS";
export const BPRODUCT_DETAILS_FAIL = "BPRODUCT_DETAILS_FAIL";

export const BPRODUCT_SAVE_REQUEST = "BPRODUCT_SAVE_REQUEST";
export const BPRODUCT_SAVE_SUCCESS = "BPRODUCT_SAVE_SUCCESS";
export const BPRODUCT_SAVE_FAIL = "BPRODUCT_SAVE_FAIL";

export const BPRODUCT_UPDATE_REQUEST = "BPRODUCT_UPDATE_REQUEST";
export const BPRODUCT_UPDATE_SUCCESS = "BPRODUCT_UPDATE_SUCCESS";
export const BPRODUCT_UPDATE_FAIL = "BPRODUCT_UPDATE_FAIL";

export const BPRODUCT_DELETE_REQUEST = "BPRODUCT_DELETE_REQUEST";
export const BPRODUCT_DELETE_SUCCESS = "BPRODUCT_DELETE_SUCCESS";
export const BPRODUCT_DELETE_FAIL = "BPRODUCT_DELETE_FAIL";



